-- El libro diario reconoce la VENTA, no solo el movimiento de plata.
--
-- Antes solo proyectaba caja: un cobro de cuota era "debe Caja / haber Cuentas
-- por Cobrar", con lo que la cuenta por cobrar bajaba sin haber subido nunca
-- (quedaba negativa), Ventas de Terrenos daba cero siempre, y el Estado de
-- Resultados mostraba solo gastos. Una empresa que vendió Bs 36.000 en lotes
-- aparecía con pérdida.
--
-- Faltaba el asiento de la venta. Al confirmarse:
--   debe  1131 Cuentas por Cobrar   precio pactado
--   haber 4111 Ventas de Terrenos   precio pactado
-- y cada pago posterior baja esa cuenta contra caja.
--
-- Un pago sobre una reserva TODAVÍA NO confirmada no es venta: es plata que se
-- le debe al comprador, y va a Anticipos de Clientes (pasivo).
--
-- Verificado con una venta de 36.000, un cobro de 9.000 y egresos por 5.200:
-- Caja 3.800, CxC 27.000, ingresos 36.000, gastos 5.200, utilidad 30.800, y
-- Activo = Pasivo + Patrimonio.
