-- Contabilidad completa: plan de cuentas editable, comprobantes manuales,
-- reexpresión monetaria por UFV y cierre de gestión.
--
-- Hasta acá la contabilidad era 100% derivada: cada asiento salía de una venta,
-- un pago o un egreso. Eso cubre la operación diaria pero deja afuera todo lo
-- que un contador registra a mano —aportes de capital, depreciaciones,
-- correcciones, el ajuste por inflación, el cierre anual— y sin eso el sistema
-- acompaña a un ERP contable en vez de reemplazarlo.
--
-- Aplicado en la base en cuatro partes:
--   contabilidad_plena_esquema   tablas y enums (chart_of_accounts editable,
--                                fiscal_periods, journal_entries/lines, ufv_rates)
--   comprobantes_rpcs            admin_save_voucher / admin_void_voucher,
--                                assert_periodo_abierto, next_voucher_number
--   diario_con_comprobantes_y_plan  v_libro_diario suma los comprobantes
--                                REGISTRADOS; admin_upsert_account /
--                                admin_delete_account
--   reexpresion_y_cierre         admin_set_ufv, ufv_at, rep_reexpresion,
--                                admin_post_reexpresion, admin_close_period,
--                                admin_reopen_period
--
-- Decisiones que no son obvias leyendo el SQL:
--
-- * El cuadre se valida al REGISTRAR, no al guardar. Un borrador a medio
--   escribir tiene que poder guardarse; exigir cuadre en cada línea obliga a
--   pelearse con el formulario en mitad de un asiento.
-- * Un comprobante registrado no se edita: se anula y se hace otro. Editar un
--   asiento ya asentado es reescribir historia contable.
-- * Solo los comprobantes REGISTRADOS entran al libro. Un borrador es un papel
--   a medio escribir y un anulado es un asiento que se decidió que no existe;
--   cualquiera de los dos en el libro mostraría plata que nadie movió.
-- * Las cuentas del sistema (1111, 1131, 4111, 5xxx…) no se borran ni cambian
--   de naturaleza: si 1111 dejara de ser activo, el balance dejaría de cuadrar
--   solo, sin que nadie haya tocado un asiento.
-- * Una cuenta CON movimientos no se borra, se desactiva: borrarla dejaría
--   asientos apuntando a una cuenta inexistente.
-- * El cierre se asienta ANTES de marcar el período cerrado — al revés, el
--   propio asiento de cierre chocaría contra la regla que acaba de imponer.
-- * Reabrir una gestión BORRA su asiento de cierre: dejarlo duplicaría el
--   resultado la próxima vez que se cierre.
-- * ufv_at() toma la última cotización anterior o igual a la fecha, no la
--   exacta: el BCB no publica feriados y un mes que termina en domingo daría
--   nulo justo al cerrarlo.
--
-- Probado de punta a punta en una transacción abortada, con venta 40.000,
-- cobro 8.000, egreso 6.000 y un aporte de capital de 50.000 por comprobante:
-- el asiento descuadrado se rechaza (NO_CUADRA), el factor UFV da 1,149303, el
-- cierre CIE-0001 arroja resultado 34.000, ingresos y gastos quedan en cero,
-- el diario sigue cuadrando, Activo 84.000 = Pasivo+Patrimonio 84.000, y un
-- comprobante con fecha dentro del período cerrado se rechaza.
